import random
import os

num_var=9
num_clau=256
file = open("uf250-test_sat.cnf","w")  #satisfiable
file.write("c This Formular is generated by mcnf\n")
file.write("c\n")
file.write("c    horn? no \n")
file.write("c    forced? no \n")
file.write("c    mixed sat? no \n")
file.write("c    clause length = 3 \n")
file.write("c\n")
file.write("p cnf "+str(num_var)+"  "+str(num_clau)+"\n")

file2 = open("uf250-test_unsat.cnf","w")  #unsatisfiable
file2.write("c This Formular is generated by mcnf\n")
file2.write("c\n")
file2.write("c    horn? no \n")
file2.write("c    forced? no \n")
file2.write("c    mixed sat? no \n")
file2.write("c    clause length = 3 \n")
file2.write("c\n")
file2.write("p cnf "+str(num_var)+"  "+str(num_clau)+"\n")

map = {}
i=0
def DFS(result,level,list):
    if(level==0):
        return list.append(result)
    else:
        DFS(result+" "+str(level),level-1,list)
        DFS(result+" "+str(-level),level-1,list)


result=""
level=9
list=[];
DFS(result,level,list)
for li in list:
    array=li.split()
    sat=0
    for i in range(0,9):
        true=0
        if(int(array[i])>0):
            true=1
        sat |= true
    if(sat==1):
        file.write(array[0]+" "+array[1]+" "+ array[2]+" 0"+"\n")
        file.write(array[3]+" "+array[4]+" "+ array[5]+" 0"+"\n")
        file.write(array[6]+" "+array[7]+" "+ array[8]+" 0"+"\n")
    else:
        file2.write(array[0]+" "+array[1]+" "+ array[2]+" 0"+"\n")
        file2.write(array[3]+" "+array[4]+" "+ array[5]+" 0"+"\n")
        file2.write(array[6]+" "+array[7]+" "+ array[8]+" 0"+"\n")

'''
for
while(i<num_clau):
    a=random.randint(-num_var,num_var)
    b=random.randint(-num_var,num_var)
    c=random.randint(-num_var,num_var)
    if (abs(a)!=abs(b) & abs(a)!=abs(c) & abs(b)!=abs(c)):
        print(i)
        key=str(a)+str(b)+str(c);
        print(key)
        if key in map:
            continue
        file.write(str(a)+" "+str(b)+" "+ str(c)+" 0"+"\n")
        map[key]=1
        i+=1
    else :
        continue
'''
